### ISSUE TITLE
Chrono-Format Numbers Inaccurate

### ISSUE THREAD

**Issue by Rick-2CA** [KevinMarquette/Chronometer#11]
I may be reading this wrong, but it looks like the formatted numbers may be off.  Take this example:

`[0318ms,020,016ms]  133:        [XML]$Report = Get-GPOReport -GUID $GPO.ID -ReportType XML

$Chrono.Line[133] | FL
	Duration   : 00:00:59.3181773
	HitCount   : 20
	Min        : 00:00:02.4815169
	Max        : 00:00:06.6411431
	Average    : 15.9
	LineNumber : 133
	Path       : C:\Users\$Env:Username\Desktop\AD_GPOAudit_WithRunSpace.ps1
	Text       :     [XML]$Report = Get-GPOReport -GUID $GPO.ID -ReportType XML
	Executions : {System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable,
				 System.Collections.Hashtable...}`

My numbers should have seconds rather than milliseconds on the output?

**Comment by KevinMarquette** [comment]
I'll dig into it. I think I saw something like this in one of my runs. 

I just refactored it to use timespan objects so I may have a bug in the formatter to track down.

**Comment by KevinMarquette** [comment]
I was using the `milliseconds` off of the `timespan` object instead of the `TotalMilliseconds`. That solves the core issue with the format not showing accurate numbers.

I do need to loop back have a way to adjust the resolution. seconds vs miliseconds, ect

**Comment by KevinMarquette** [comment]
Resolved in release 0.5.3.44, published to PSGallery

**Comment by Rick-2CA** [comment]
Thank you, Sir.
