### ISSUE TITLE
Merge modules

### ISSUE THREAD

**Issue by oliwex** [KevinMarquette/Chronometer#32]
Recently i saw module called Profiler/Profile. Could you update yours or merge few functionalities with Profiler. For example:
![image](https://user-images.githubusercontent.com/29152066/128166358-fe139af8-1a32-4e85-b8db-e2a63663e724.png)
 and just write docs for this like you do with psgraph ( readthedocs or something i saw)

**Comment by KevinMarquette** [comment]
I added a link to https://github.com/IISResetMe/PSProfiler in the readme
